# CI Tool Configuration
server:
  workspace: "workspace"

git:
  accessToken: ${GIT_ACCESS_TOKEN}

jobs:
  - name: "Example"
    repo_url: ${GIT_REPO_URL}
    watch_files:
      - "src/*.py"
      - "requirements.txt"
    script: "scripts\\build.cmd"
    target_branch: "main"
